Fix returns on iOS
Instabug/Instabug-Flutter pull request #205
Opened 2021-09-29 14:44 UTC by via-guy

## Summary of Changes
Fixes #191

As mentioned in the issue, my fix for returning from method calls to iOS was undone for an unknown reason. It blocks returns when calling `await` on `Instabug` calls from iOS. It's a pretty serious issue.

I've also re-enabled the `unawaited_futures` analysis option to show that it works now.

## Checklist
- [x] In addition to adding the new API to Dart, I have also added its implementation to both iOS and Android.
- [x] I have added at least 1 unit test in Dart for the new API and made sure the tests pass locally.
- [x] I have updated [README.md](https://github.com/Instabug/Instabug-Flutter/blob/master/README.md) to add the new API.

2022-01-06 06:37 UTC, via-guy commented
@AliAbdelfattah @ymabdallah can one of you please look into this? It's a serious issue with the code.

2022-01-06 06:38 UTC, via-guy commented on ios/Classes/InstabugFlutterPlugin.m
> +                result(nil);
This is the important fix. If you don't call the completion block then the Dart code will never complete the Future.

2022-02-08 10:11 UTC, via-guy commented
@ahmed1hisham @AliAbdelfattah @ymabdallah can someone please review this?

2022-02-08 11:20 UTC, AliAbdelfattah commented
@via-guy sorry this's been taking long, we'll try to prioritize this 👌

2022-02-08 11:21 UTC, InstabugCI commented
<!--
  0 Errors
  1 Warning: Please include a CHANGELOG ent...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry. <br />
You can find it at <a href="https://github.com/Instabug/Instabug-Flutter/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2022-02-18 09:36 UTC, via-guy commented
@AliAbdelfattah added missing CHANGELOG entry. Can you please check it?

2022-02-21 17:52 UTC, via-guy commented
@AliAbdelfattah we've been waiting months for this. Please can you look into merging it?

2022-03-02 15:40 UTC, TheBuggedYRN requested changes
Sorry for the late response @via-guy. We are working on this now, and it will get merged as soon as we resolve the comments.

2022-03-03 08:32 UTC, TheBuggedYRN commented
We need to exclude other changes from 25da1ca7b3cddf1276ed28e747aeeaebfae25ed8, too.

2022-03-03 08:41 UTC, TheBuggedYRN requested changes
We need to exclude other changes from https://github.com/Instabug/Instabug-Flutter/commit/25da1ca7b3cddf1276ed28e747aeeaebfae25ed8, too.

2022-03-03 09:27 UTC, via-guy commented
@TheBuggedYRN done

2022-03-03 12:21 UTC, TheBuggedYRN commented
Please [allow edit from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests), because we need to modify some unit tests related to this issue.

2022-03-03 13:26 UTC, via-guy commented
@TheBuggedYRN it's already enabled

2022-03-06 11:18 UTC, TheBuggedYRN approved these changes

2022-03-06 11:20 UTC, merged

2022-03-06 11:20 UTC, TheBuggedYRN commented
Thanks @via-guy for your contribution!