Feat:add non fatal api
Instabug/Instabug-Flutter pull request #461
Opened 2024-04-27 13:43 UTC by ahmedAlaaInstabug

## Description of the change
1. add non-fatal API
## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Related issues

JIRA ID: MOB-13793

### Development
- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
### Code review 
- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] Issue from task tracker has a link to this pull request

2024-04-27 13:46 UTC, InstabugCI commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### Coverage Report
| Label | Coverage | Status |
| ----- | -------- | ------ |
| Dart | 82.6% | ✅ |
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 047c2a896fc313eb78187045ebfed97d3049af40
</p>

2024-04-29 12:50 UTC, AndrewAminInstabug commented on android/src/main/java/com/instabug/flutter/modules/CrashReportingApi.java
> +//                Method getFingerPrintMethod = Reflection.getMethod(Class.forName("com.instabug.crash.CrashReporting"), "getFingerprintObject", String.class);
please remove hashed code

2024-04-29 13:37 UTC, a7medev requested changes
Good job @ahmedAlaaInstabug! 👏🏼 I have added some comments so please check them and let me know your thoughts. 🙏🏼

Side note: some iOS code/tests are broken because the snapshot is on `v12.7.1` which doesn't contain App Flows and this branch's base has App Flows in it.

2024-04-29 13:37 UTC, a7medev commented on example/ios/InstabugTests/CrashReportingApiTests.m
> +              ]);
Just a little bit of formatting for Objective-C 😅

```suggestion
    NSString *fingerprint = @"fingerprint";
    NSDictionary *userAttributes = @{ @"key" : @"value" };
    NSString *level = @"NonFatalExceptionLevel.error";
    
    FlutterError *error;
    
    [self.api sendNonFatalErrorJsonCrash:jsonCrash
                          userAttributes:userAttributes
                             fingerprint:fingerprint
                  nonFatalExceptionLevel:level
                                   error:&error];
    
    OCMVerify([self.mCrashReporting cp_reportNonFatalCrashWithStackTrace:@{}
                                                                   level:IBGNonFatalLevelError
                                                          groupingString:fingerprint
                                                          userAttributes:userAttributes]);
```

2024-04-29 13:37 UTC, a7medev commented on ios/Classes/Modules/CrashReportingApi.m
>      }
We can better cast `isHandled` to `BOOL` and rename the `value` variable to something like `isNonFatal` for clarity, and a little bit of formatting. What do you think?

```suggestion
    BOOL isNonFatal = [isHandled boolValue];
    if (isNonFatal) {
        [IBGCrashReporting cp_reportNonFatalCrashWithStackTrace:stackTrace
                                                          level:IBGNonFatalLevelError
                                                 groupingString:nil
                                                 userAttributes:nil];
    } else {
        [IBGCrashReporting cp_reportFatalCrashWithStackTrace:stackTrace];
    }
```

2024-04-29 14:37 UTC, a7medev submitted a review, later dismissed
Perfetto! 👌🏼

2024-04-29 15:02 UTC, AndrewAminInstabug approved these changes

2024-06-11 01:27 UTC, merged