refator: monoRepo
Instabug/Instabug-Flutter pull request #519
Opened 2024-10-17 23:38 UTC by ahmedAlaaInstabug

## Description of the change
Create monorepo for instabug-flutter 
## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Related issues
JIRA ID : MOB-16329
## Checklists
### Development
- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
### Code review 
- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] Issue from task tracker has a link to this pull request

2024-10-18 04:11 UTC, InstabugCI commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### Coverage Report
| Label | Coverage | Status |
| ----- | -------- | ------ |
| Dart | 85.3% | ✅ |
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4e4c9a77b6b2ef90f49672c4f1f32feb68b59e40
</p>

2024-10-27 07:35 UTC, a7medev requested changes
Amazing effort on this @ahmedAlaaInstabug 👏🏼❤️

I feel like we can rename `packages/Instabug-Flutter` to the actual pub.dev package name `packages/instabug_flutter`, we can do the same for the rest of the packages once added as well.
An alternative would be to rename it to `core` and the rest would be `dio`, `http`, `flutter_modular` etc.
What do you think?

2024-10-27 07:35 UTC, a7medev commented on .gitignore
> +packages/**ios/**/Generated/
```suggestion
packages/**/ios/**/Generated/
```

2024-10-27 07:35 UTC, a7medev commented on .gitignore
> +/packages/Instabug-Flutter/lib/src/generated/
I feel like this could be more general in case we added Pigeon to other packages as well.
```suggestion
/packages/**/lib/src/generated/
```

2025-02-27 10:48 UTC, AndrewAminInstabug reviewed
@ahmedAlaaInstabug excellent job, kindly resolve the CI jobs that failed

2025-09-16 07:36 UTC, closed without merging