fix/send-screen-name-as-null
Instabug/Instabug-Flutter pull request #529
Opened 2024-11-07 11:55 UTC by ahmedAlaaInstabug

## Description of the change
1) fix sending Screen name as null
## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Related issues
JIRA ID : INSD-12529
## Checklists
### Development
- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
### Code review 
- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] Issue from task tracker has a link to this pull request

2024-11-07 11:58 UTC, InstabugCI commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### Coverage Report
| Label | Coverage | Status |
| ----- | -------- | ------ |
| Dart | 85.3% | ✅ |
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 039b389112518410f2c58be4a62965237fdcc439
</p>

2024-11-07 12:36 UTC, AndrewAminInstabug approved these changes

2024-12-03 07:41 UTC, a7medev commented
As mentioned in #528, changing this behavior from `null` to `N/A` will affect screens grouping on the dashboard and so we need to mention that in the breaking changes. Besides, is that really a bug? There's still a name reported on the dashboard even though it's just `null` 🤔

2024-12-03 07:42 UTC, a7medev requested changes
As mentioned in #528, changing this behavior from `null` to `N/A` will affect screens grouping on the dashboard and so we need to mention that in the breaking changes. Besides, is that really a bug? There's still a name reported on the dashboard even though it's just `null` 🤔

2024-12-22 09:50 UTC, closed without merging